// Interface Logger - Sistemas Distribuídos - PUCPR
//
// Grupo T1-15: Alana da Conceição Queiroz, Larissa Alves da Silva,
//              Leticia Maria Maia de Andrade Vieira, Thomas Manussadjian Steinhausser

enum Severidade { DEBUG, WARNING, ERROR, CRITICAL };

exception SeveridadeInexistente {};

interface Logger {

    // notificação assíncrona de um evento (oneway: sem retorno)
    oneway void log(in Severidade severidade,
                    in string endereco,
                    in unsigned short pid,
                    in long hora,
                    in string msg);

    // endereço ("ip:porta") do último evento recebido com severidade s
    string locate(in Severidade s) raises (SeveridadeInexistente);
};
